spring:
  application:
    name: spring-ai-alibaba-bailian-example

  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen3.8-27b

  profiles:
    active: agent
