server:
  port: 10000

spring:
  application:
    name: issue-clarify-example
  ai:
    dashscope:
      index-name: test_knowledge
      api-key: ${AI_DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen3.8-27b
          multi-model: true
