server:
  port: 8081

spring:
  application:
    name: voice-agent-dashcope-sdk-example
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen3.8-27b
